### ISSUE TITLE
The visible function reports an error.

### ISSUE THREAD

**Issue by serenez** [jlchmura/lpc-language-server#46]
This visible function reports an error. I don't know why.
![image](https://github.com/user-attachments/assets/95e918f6-02ea-4b03-a712-b4c11497b7c0)
![image](https://github.com/user-attachments/assets/15529274-682d-4f95-a942-bf2e69093c87)

**Comment by serenez** [comment]
Here's another error that came up when I tried to write an already defined #define

``OnCompletion file:///e%3A/24xinduobao/d/xinshoucun/npc/tianji.c
[Error - 11:59:46] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'column')
  Code: -32603 
 303.3212ms | completion
   0.0122ms | semantic-token-request
   0.0133ms | semantic-token-request
TypeError: Cannot read properties of undefined (reading 'tokenIndex')
    at PrimaryExpressionContext.getSourceInterval (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:17452:60)
    at findRecursive (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:37228:29)
    at findRecursive (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:37231:21)
    at findRecursive (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:37231:21)
    at ContextSymbolTable.symbolContainingContext (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:37241:12)
    at _SourceContext.symbolAtPosition (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:74840:35)
    at LpcFacade.symbolInfoAtPosition (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:75706:21)
    at HoverProvider.getHover (c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:76127:37)
    at c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:76948:43
    at c:\Users\Administrator.vscode\extensions\jlchmura.lpc-1.0.25\out\server\src\server.js:8161:18
   0.0157ms | semantic-token-request
   0.0196ms | semantic-token-request `
`
![image](https://github.com/user-attachments/assets/a9abfb03-e290-40da-8390-9585265aa46f)

**Comment by jlchmura** [comment]
Fixed in v27
